/** Declaration file generated by dts-gen */

export class IPCEventEmitter {
    constructor($process: any, ...args: any[]);

    addListener(name: any, listener: any): any;

    emit(...args: any[]): any;

    on(name: any, listener: any): any;

    once(name: any, listener: any): any;

    pin(name: any, ...args: any[]): any;

    prependListener(name: any, listener: any): any;

    prependOnceListener(name: any, listener: any): any;

    unpin(name: any): any;

    static defaultMaxListeners: number;

    static init(): void;

    static listenerCount(emitter: any, type: any): any;

    static usingDomains: boolean;

}

export namespace IPCEventEmitter {
    class EventEmitter {
        constructor();

        addListener(type: any, listener: any): any;

        emit(type: any, args: any): any;

        eventNames(): any;

        getMaxListeners(): any;

        listenerCount(type: any): any;

        listeners(type: any): any;

        off(type: any, listener: any): any;

        on(type: any, listener: any): any;

        once(type: any, listener: any): any;

        prependListener(type: any, listener: any): any;

        prependOnceListener(type: any, listener: any): any;

        rawListeners(type: any): any;

        removeAllListeners(type: any, ...args: any[]): any;

        removeListener(type: any, listener: any): any;

        setMaxListeners(n: any): any;

        static EventEmitter: any;

        static defaultMaxListeners: number;

        static init(): void;

        static listenerCount(emitter: any, type: any): any;

        static usingDomains: boolean;

    }

}

